#include "Analyse.hpp"

namespace ba
{
    Analyse::~Analyse()
    {
    }

    Analyse::Analyse(TTree& tree) : tree_(tree)
    {
        // Set object pointer
        El_E = 0;
        El_px = 0;
        El_py = 0;
        El_pz = 0;
        El_charge = 0;
        El_pdgId = 0;
        El_EtaCorrMag = 0;
        El_EoverP = 0;
        El_deltaEta1 = 0;
        El_deltaEta2 = 0;
        El_deltaPhi2 = 0;
        El_etcone20 = 0;
        El_T_El_DeltaR = 0;
        Mu_E = 0;
        Mu_p_T = 0;
        Mu_phi = 0;
        Mu_eta = 0;
        Mu_px = 0;
        Mu_py = 0;
        Mu_pz = 0;
        Mu_m = 0;
        Mu_charge = 0;
        Mu_pdgId = 0;
        Mu_etcone40 = 0;
        Mu_nucone40 = 0;
        Mu_etcone20 = 0;
        Mu_matchChi2 = 0;
        Mu_matchChi2OverDoF = 0;
        Mu_SumTrkPtInCone = 0;
        Mu_T_Mu_DeltaR = 0;
        JetC4T_E = 0;
        JetC4T_px = 0;
        JetC4T_py = 0;
        JetC4T_pz = 0;
        JetC4T_charge = 0;
        JetC4T_pdgId = 0;
        JetC4T_weight = 0;
        JetC4T_SoftMuonWeight = 0;
        JetC4T_SoftElectronWeight = 0;
        JetC4T_IP1D = 0;
        JetC4T_IP2D = 0;
        JetC4T_IP3D = 0;
        JetC4T_SV1 = 0;
        JetC4T_SecVtxTagBU = 0;
        JetC4T_SV2 = 0;
        JetC4T_T_Jet_DeltaR = 0;
        JetC4T_T_El_DeltaR = 0;
        JetC4T_T_Ph_DeltaR = 0;
#ifdef BA_TRUTH_VARIABLES
        T_Mu_E = 0;
        T_Mu_p_T = 0;
        T_Mu_phi = 0;
        T_Mu_eta = 0;
        T_Mu_px = 0;
        T_Mu_py = 0;
        T_Mu_pz = 0;
        T_Mu_m = 0;
        T_Mu_charge = 0;
        T_Mu_pdgId = 0;
        T_El_E = 0;
        T_El_p_T = 0;
        T_El_phi = 0;
        T_El_eta = 0;
        T_El_px = 0;
        T_El_py = 0;
        T_El_pz = 0;
        T_El_m = 0;
        T_El_charge = 0;
        T_El_pdgId = 0;
        T_JetC4_E = 0;
        T_JetC4_p_T = 0;
        T_JetC4_phi = 0;
        T_JetC4_eta = 0;
        T_JetC4_px = 0;
        T_JetC4_py = 0;
        T_JetC4_pz = 0;
        T_JetC4_m = 0;
        T_JetC4_charge = 0;
        T_JetC4_pdgId = 0;
        T_JetC4_T_El_DeltaR = 0;
        T_JetC4_T_Mu_DeltaR = 0;
        T_JetC4_T_Ph_DeltaR = 0;
        T_JetC4_T_Jet_DeltaR = 0;
        El_IsEM = 0;
        Mu_hasCluster = 0;
        Mu_hasCombinedMuon = 0;
        JetC4T_SoftMuonNumTrack = 0;
        JetC4T_SoftElectronNumTrack = 0;
        JetC4T_T_Jet_Matched = 0;
        JetC4T_T_El_Matched = 0;
        JetC4T_T_Ph_Matched = 0;
        T_Mu_nParents = 0;
        T_Mu_nDecay = 0;
        T_El_nParents = 0;
        T_El_nDecay = 0;
        T_JetC4_T_El_Matched = 0;
        T_JetC4_T_Mu_Matched = 0;
        T_JetC4_T_Ph_Matched = 0;
        T_JetC4_T_Jet_Matched = 0;
        T_El_ParentIDs = 0;
        T_Mu_ParentIDs = 0;
        T_Mu_ParentBarcodes = 0;
        T_Mu_ParentStatus = 0;
        T_Mu_ParentPt = 0;
        T_Mu_ParentEta = 0;
        T_Mu_DecayIDs = 0;
        T_Mu_DecayBarcodes = 0;
        T_Mu_DecayStatus = 0;
        T_Mu_DecayPt = 0;
        T_Mu_DecayEta = 0;
        T_El_DecayIDs = 0;
        T_El_ParentBarcodes = 0;
        T_El_DecayBarcodes = 0;
        T_El_ParentStatus = 0;
        T_El_DecayStatus = 0;
        T_El_DecayPt = 0;
        T_El_DecayEta = 0;
        T_El_ParentPt = 0;
        T_El_ParentEta = 0;
#endif

        tree_.SetBranchAddress("MET_RefFinal_ex", &MET_RefFinal_ex);
        tree_.SetBranchAddress("MET_RefFinal_ey", &MET_RefFinal_ey);
        tree_.SetBranchAddress("MET_RefFinal_et", &MET_RefFinal_et);
        tree_.SetBranchAddress("MET_RefFinal_sumet", &MET_RefFinal_sumet);
        tree_.SetBranchAddress("MET_RefEle_ex", &MET_RefEle_ex);
        tree_.SetBranchAddress("MET_RefEle_ey", &MET_RefEle_ey);
        tree_.SetBranchAddress("MET_RefEle_et", &MET_RefEle_et);
        tree_.SetBranchAddress("MET_RefEle_sumet", &MET_RefEle_sumet);
        tree_.SetBranchAddress("MET_RefMuon_ex", &MET_RefMuon_ex);
        tree_.SetBranchAddress("MET_RefMuon_ey", &MET_RefMuon_ey);
        tree_.SetBranchAddress("MET_RefMuon_et", &MET_RefMuon_et);
        tree_.SetBranchAddress("MET_RefMuon_sumet", &MET_RefMuon_sumet);
        tree_.SetBranchAddress("MET_RefJet_ex", &MET_RefJet_ex);
        tree_.SetBranchAddress("MET_RefJet_ey", &MET_RefJet_ey);
        tree_.SetBranchAddress("MET_RefJet_et", &MET_RefJet_et);
        tree_.SetBranchAddress("MET_RefJet_sumet", &MET_RefJet_sumet);
        tree_.SetBranchAddress("MET_RefGamma_ex", &MET_RefGamma_ex);
        tree_.SetBranchAddress("MET_RefGamma_ey", &MET_RefGamma_ey);
        tree_.SetBranchAddress("MET_RefGamma_et", &MET_RefGamma_et);
        tree_.SetBranchAddress("MET_RefGamma_sumet", &MET_RefGamma_sumet);
        tree_.SetBranchAddress("MET_CellOut_ex", &MET_CellOut_ex);
        tree_.SetBranchAddress("MET_CellOut_ey", &MET_CellOut_ey);
        tree_.SetBranchAddress("MET_CellOut_et", &MET_CellOut_et);
        tree_.SetBranchAddress("MET_CellOut_sumet", &MET_CellOut_sumet);
        tree_.SetBranchAddress("MET_MuonBoy_ex", &MET_MuonBoy_ex);
        tree_.SetBranchAddress("MET_MuonBoy_ey", &MET_MuonBoy_ey);
        tree_.SetBranchAddress("MET_MuonBoy_et", &MET_MuonBoy_et);
        tree_.SetBranchAddress("MET_MuonBoy_sumet", &MET_MuonBoy_sumet);
        tree_.SetBranchAddress("MET_CryoCone_ex", &MET_CryoCone_ex);
        tree_.SetBranchAddress("MET_CryoCone_ey", &MET_CryoCone_ey);
        tree_.SetBranchAddress("MET_CryoCone_et", &MET_CryoCone_et);
        tree_.SetBranchAddress("MET_CryoCone_sumet", &MET_CryoCone_sumet);
        tree_.SetBranchAddress("MET_LocHadTopoObj_ex", &MET_LocHadTopoObj_ex);
        tree_.SetBranchAddress("MET_LocHadTopoObj_ey", &MET_LocHadTopoObj_ey);
        tree_.SetBranchAddress("MET_LocHadTopoObj_et", &MET_LocHadTopoObj_et);
        tree_.SetBranchAddress("MET_LocHadTopoObj_sumet", &MET_LocHadTopoObj_sumet);
        tree_.SetBranchAddress("MET_LocHadTopo_ex", &MET_LocHadTopo_ex);
        tree_.SetBranchAddress("MET_LocHadTopo_ey", &MET_LocHadTopo_ey);
        tree_.SetBranchAddress("MET_LocHadTopo_et", &MET_LocHadTopo_et);
        tree_.SetBranchAddress("MET_LocHadTopo_sumet", &MET_LocHadTopo_sumet);
        tree_.SetBranchAddress("MET_Truth_Int_ex", &MET_Truth_Int_ex);
        tree_.SetBranchAddress("MET_Truth_Int_ey", &MET_Truth_Int_ey);
        tree_.SetBranchAddress("MET_Truth_Int_et", &MET_Truth_Int_et);
        tree_.SetBranchAddress("MET_Truth_Int_sumet", &MET_Truth_Int_sumet);
        tree_.SetBranchAddress("MET_Truth_NonInt_ex", &MET_Truth_NonInt_ex);
        tree_.SetBranchAddress("MET_Truth_NonInt_ey", &MET_Truth_NonInt_ey);
        tree_.SetBranchAddress("MET_Truth_NonInt_et", &MET_Truth_NonInt_et);
        tree_.SetBranchAddress("MET_Truth_NonInt_sumet", &MET_Truth_NonInt_sumet);
        tree_.SetBranchAddress("MET_Truth_IntCentral_ex", &MET_Truth_IntCentral_ex);
        tree_.SetBranchAddress("MET_Truth_IntCentral_ey", &MET_Truth_IntCentral_ey);
        tree_.SetBranchAddress("MET_Truth_IntCentral_et", &MET_Truth_IntCentral_et);
        tree_.SetBranchAddress("MET_Truth_IntCentral_sumet", &MET_Truth_IntCentral_sumet);
        tree_.SetBranchAddress("MET_Truth_IntFwd_ex", &MET_Truth_IntFwd_ex);
        tree_.SetBranchAddress("MET_Truth_IntFwd_ey", &MET_Truth_IntFwd_ey);
        tree_.SetBranchAddress("MET_Truth_IntFwd_et", &MET_Truth_IntFwd_et);
        tree_.SetBranchAddress("MET_Truth_IntFwd_sumet", &MET_Truth_IntFwd_sumet);
        tree_.SetBranchAddress("MET_Truth_IntOutCover_ex", &MET_Truth_IntOutCover_ex);
        tree_.SetBranchAddress("MET_Truth_IntOutCover_ey", &MET_Truth_IntOutCover_ey);
        tree_.SetBranchAddress("MET_Truth_IntOutCover_et", &MET_Truth_IntOutCover_et);
        tree_.SetBranchAddress("MET_Truth_IntOutCover_sumet", &MET_Truth_IntOutCover_sumet);
        tree_.SetBranchAddress("MET_Truth_Muons_ex", &MET_Truth_Muons_ex);
        tree_.SetBranchAddress("MET_Truth_Muons_ey", &MET_Truth_Muons_ey);
        tree_.SetBranchAddress("MET_Truth_Muons_et", &MET_Truth_Muons_et);
        tree_.SetBranchAddress("MET_Truth_Muons_sumet", &MET_Truth_Muons_sumet);
        tree_.SetBranchAddress("MET_Truth_PileUp_Int_ex", &MET_Truth_PileUp_Int_ex);
        tree_.SetBranchAddress("MET_Truth_PileUp_Int_ey", &MET_Truth_PileUp_Int_ey);
        tree_.SetBranchAddress("MET_Truth_PileUp_Int_et", &MET_Truth_PileUp_Int_et);
        tree_.SetBranchAddress("MET_Truth_PileUp_Int_sumet", &MET_Truth_PileUp_Int_sumet);
        tree_.SetBranchAddress("MET_Truth_PileUp_NonInt_ex", &MET_Truth_PileUp_NonInt_ex);
        tree_.SetBranchAddress("MET_Truth_PileUp_NonInt_ey", &MET_Truth_PileUp_NonInt_ey);
        tree_.SetBranchAddress("MET_Truth_PileUp_NonInt_et", &MET_Truth_PileUp_NonInt_et);
        tree_.SetBranchAddress("MET_Truth_PileUp_NonInt_sumet", &MET_Truth_PileUp_NonInt_sumet);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntCentral_ex", &MET_Truth_PileUp_IntCentral_ex);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntCentral_ey", &MET_Truth_PileUp_IntCentral_ey);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntCentral_et", &MET_Truth_PileUp_IntCentral_et);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntCentral_sumet", &MET_Truth_PileUp_IntCentral_sumet);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntFwd_ex", &MET_Truth_PileUp_IntFwd_ex);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntFwd_ey", &MET_Truth_PileUp_IntFwd_ey);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntFwd_et", &MET_Truth_PileUp_IntFwd_et);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntFwd_sumet", &MET_Truth_PileUp_IntFwd_sumet);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntOutCover_ex", &MET_Truth_PileUp_IntOutCover_ex);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntOutCover_ey", &MET_Truth_PileUp_IntOutCover_ey);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntOutCover_et", &MET_Truth_PileUp_IntOutCover_et);
        tree_.SetBranchAddress("MET_Truth_PileUp_IntOutCover_sumet", &MET_Truth_PileUp_IntOutCover_sumet);
        tree_.SetBranchAddress("MET_Truth_PileUp_Muons_ex", &MET_Truth_PileUp_Muons_ex);
        tree_.SetBranchAddress("MET_Truth_PileUp_Muons_ey", &MET_Truth_PileUp_Muons_ey);
        tree_.SetBranchAddress("MET_Truth_PileUp_Muons_et", &MET_Truth_PileUp_Muons_et);
        tree_.SetBranchAddress("MET_Truth_PileUp_Muons_sumet", &MET_Truth_PileUp_Muons_sumet);
        tree_.SetBranchAddress("El_N", &El_N);
        tree_.SetBranchAddress("Mu_N", &Mu_N);
        tree_.SetBranchAddress("JetC4T_N", &JetC4T_N);
        tree_.SetBranchAddress("El_E", &El_E);
        tree_.SetBranchAddress("El_px", &El_px);
        tree_.SetBranchAddress("El_py", &El_py);
        tree_.SetBranchAddress("El_pz", &El_pz);
        tree_.SetBranchAddress("El_charge", &El_charge);
        tree_.SetBranchAddress("El_pdgId", &El_pdgId);
        tree_.SetBranchAddress("El_EtaCorrMag", &El_EtaCorrMag);
        tree_.SetBranchAddress("El_EoverP", &El_EoverP);
        tree_.SetBranchAddress("El_deltaEta1", &El_deltaEta1);
        tree_.SetBranchAddress("El_deltaEta2", &El_deltaEta2);
        tree_.SetBranchAddress("El_deltaPhi2", &El_deltaPhi2);
        tree_.SetBranchAddress("El_etcone20", &El_etcone20);
        tree_.SetBranchAddress("El_T_El_DeltaR", &El_T_El_DeltaR);
        tree_.SetBranchAddress("Mu_E", &Mu_E);
        tree_.SetBranchAddress("Mu_px", &Mu_px);
        tree_.SetBranchAddress("Mu_py", &Mu_py);
        tree_.SetBranchAddress("Mu_pz", &Mu_pz);
        tree_.SetBranchAddress("Mu_charge", &Mu_charge);
        tree_.SetBranchAddress("Mu_pdgId", &Mu_pdgId);
        tree_.SetBranchAddress("Mu_etcone40", &Mu_etcone40);
        tree_.SetBranchAddress("Mu_nucone40", &Mu_nucone40);
        tree_.SetBranchAddress("Mu_etcone20", &Mu_etcone20);
        tree_.SetBranchAddress("Mu_matchChi2", &Mu_matchChi2);
        tree_.SetBranchAddress("Mu_matchChi2OverDoF", &Mu_matchChi2OverDoF);
        tree_.SetBranchAddress("Mu_SumTrkPtInCone", &Mu_SumTrkPtInCone);
        tree_.SetBranchAddress("Mu_T_Mu_DeltaR", &Mu_T_Mu_DeltaR);
        tree_.SetBranchAddress("JetC4T_E", &JetC4T_E);
        tree_.SetBranchAddress("JetC4T_px", &JetC4T_px);
        tree_.SetBranchAddress("JetC4T_py", &JetC4T_py);
        tree_.SetBranchAddress("JetC4T_pz", &JetC4T_pz);
        tree_.SetBranchAddress("JetC4T_charge", &JetC4T_charge);
        tree_.SetBranchAddress("JetC4T_pdgId", &JetC4T_pdgId);
        tree_.SetBranchAddress("JetC4T_weight", &JetC4T_weight);
        tree_.SetBranchAddress("JetC4T_SoftMuonWeight", &JetC4T_SoftMuonWeight);
        tree_.SetBranchAddress("JetC4T_SoftElectronWeight", &JetC4T_SoftElectronWeight);
        tree_.SetBranchAddress("JetC4T_IP1D", &JetC4T_IP1D);
        tree_.SetBranchAddress("JetC4T_IP2D", &JetC4T_IP2D);
        tree_.SetBranchAddress("JetC4T_IP3D", &JetC4T_IP3D);
        tree_.SetBranchAddress("JetC4T_SV1", &JetC4T_SV1);
        tree_.SetBranchAddress("JetC4T_SecVtxTagBU", &JetC4T_SecVtxTagBU);
        tree_.SetBranchAddress("JetC4T_SV2", &JetC4T_SV2);
        tree_.SetBranchAddress("JetC4T_T_Jet_DeltaR", &JetC4T_T_Jet_DeltaR);
        tree_.SetBranchAddress("JetC4T_T_El_DeltaR", &JetC4T_T_El_DeltaR);
        tree_.SetBranchAddress("JetC4T_T_Ph_DeltaR", &JetC4T_T_Ph_DeltaR);
#ifdef BA_TRUTH_VARIABLES
        tree_.SetBranchAddress("T_Mu_N", &T_Mu_N);
        tree_.SetBranchAddress("T_El_N", &T_El_N);
        tree_.SetBranchAddress("T_JetC4_N", &T_JetC4_N);
        tree_.SetBranchAddress("T_Mu_E", &T_Mu_E);
        tree_.SetBranchAddress("T_Mu_p_T", &T_Mu_p_T);
        tree_.SetBranchAddress("T_Mu_phi", &T_Mu_phi);
        tree_.SetBranchAddress("T_Mu_eta", &T_Mu_eta);
        tree_.SetBranchAddress("T_Mu_px", &T_Mu_px);
        tree_.SetBranchAddress("T_Mu_py", &T_Mu_py);
        tree_.SetBranchAddress("T_Mu_pz", &T_Mu_pz);
        tree_.SetBranchAddress("T_Mu_m", &T_Mu_m);
        tree_.SetBranchAddress("T_Mu_charge", &T_Mu_charge);
        tree_.SetBranchAddress("T_Mu_pdgId", &T_Mu_pdgId);
        tree_.SetBranchAddress("T_El_E", &T_El_E);
        tree_.SetBranchAddress("T_El_p_T", &T_El_p_T);
        tree_.SetBranchAddress("T_El_phi", &T_El_phi);
        tree_.SetBranchAddress("T_El_eta", &T_El_eta);
        tree_.SetBranchAddress("T_El_px", &T_El_px);
        tree_.SetBranchAddress("T_El_py", &T_El_py);
        tree_.SetBranchAddress("T_El_pz", &T_El_pz);
        tree_.SetBranchAddress("T_El_m", &T_El_m);
        tree_.SetBranchAddress("T_El_charge", &T_El_charge);
        tree_.SetBranchAddress("T_El_pdgId", &T_El_pdgId);
        tree_.SetBranchAddress("T_JetC4_E", &T_JetC4_E);
        tree_.SetBranchAddress("T_JetC4_p_T", &T_JetC4_p_T);
        tree_.SetBranchAddress("T_JetC4_phi", &T_JetC4_phi);
        tree_.SetBranchAddress("T_JetC4_eta", &T_JetC4_eta);
        tree_.SetBranchAddress("T_JetC4_px", &T_JetC4_px);
        tree_.SetBranchAddress("T_JetC4_py", &T_JetC4_py);
        tree_.SetBranchAddress("T_JetC4_pz", &T_JetC4_pz);
        tree_.SetBranchAddress("T_JetC4_m", &T_JetC4_m);
        tree_.SetBranchAddress("T_JetC4_charge", &T_JetC4_charge);
        tree_.SetBranchAddress("T_JetC4_pdgId", &T_JetC4_pdgId);
        tree_.SetBranchAddress("T_JetC4_T_El_DeltaR", &T_JetC4_T_El_DeltaR);
        tree_.SetBranchAddress("T_JetC4_T_Mu_DeltaR", &T_JetC4_T_Mu_DeltaR);
        tree_.SetBranchAddress("T_JetC4_T_Ph_DeltaR", &T_JetC4_T_Ph_DeltaR);
        tree_.SetBranchAddress("T_JetC4_T_Jet_DeltaR", &T_JetC4_T_Jet_DeltaR);
        tree_.SetBranchAddress("El_IsEM", &El_IsEM);
        tree_.SetBranchAddress("Mu_hasCluster", &Mu_hasCluster);
        tree_.SetBranchAddress("Mu_hasCombinedMuon", &Mu_hasCombinedMuon);
        tree_.SetBranchAddress("JetC4T_SoftMuonNumTrack", &JetC4T_SoftMuonNumTrack);
        tree_.SetBranchAddress("JetC4T_SoftElectronNumTrack", &JetC4T_SoftElectronNumTrack);
        tree_.SetBranchAddress("JetC4T_T_Jet_Matched", &JetC4T_T_Jet_Matched);
        tree_.SetBranchAddress("JetC4T_T_El_Matched", &JetC4T_T_El_Matched);
        tree_.SetBranchAddress("JetC4T_T_Ph_Matched", &JetC4T_T_Ph_Matched);
        tree_.SetBranchAddress("T_Mu_nParents", &T_Mu_nParents);
        tree_.SetBranchAddress("T_Mu_nDecay", &T_Mu_nDecay);
        tree_.SetBranchAddress("T_El_nParents", &T_El_nParents);
        tree_.SetBranchAddress("T_El_nDecay", &T_El_nDecay);
        tree_.SetBranchAddress("T_JetC4_T_El_Matched", &T_JetC4_T_El_Matched);
        tree_.SetBranchAddress("T_JetC4_T_Mu_Matched", &T_JetC4_T_Mu_Matched);
        tree_.SetBranchAddress("T_JetC4_T_Ph_Matched", &T_JetC4_T_Ph_Matched);
        tree_.SetBranchAddress("T_JetC4_T_Jet_Matched", &T_JetC4_T_Jet_Matched);
        tree_.SetBranchAddress("T_El_ParentIDs", &T_El_ParentIDs);
        tree_.SetBranchAddress("T_Mu_ParentIDs", &T_Mu_ParentIDs);
        tree_.SetBranchAddress("T_Mu_ParentBarcodes", &T_Mu_ParentBarcodes);
        tree_.SetBranchAddress("T_Mu_ParentStatus", &T_Mu_ParentStatus);
        tree_.SetBranchAddress("T_Mu_ParentPt", &T_Mu_ParentPt);
        tree_.SetBranchAddress("T_Mu_ParentEta", &T_Mu_ParentEta);
        tree_.SetBranchAddress("T_Mu_DecayIDs", &T_Mu_DecayIDs);
        tree_.SetBranchAddress("T_Mu_DecayBarcodes", &T_Mu_DecayBarcodes);
        tree_.SetBranchAddress("T_Mu_DecayStatus", &T_Mu_DecayStatus);
        tree_.SetBranchAddress("T_Mu_DecayPt", &T_Mu_DecayPt);
        tree_.SetBranchAddress("T_Mu_DecayEta", &T_Mu_DecayEta);
        tree_.SetBranchAddress("T_El_DecayIDs", &T_El_DecayIDs);
        tree_.SetBranchAddress("T_El_ParentBarcodes", &T_El_ParentBarcodes);
        tree_.SetBranchAddress("T_El_DecayBarcodes", &T_El_DecayBarcodes);
        tree_.SetBranchAddress("T_El_ParentStatus", &T_El_ParentStatus);
        tree_.SetBranchAddress("T_El_DecayStatus", &T_El_DecayStatus);
        tree_.SetBranchAddress("T_El_DecayPt", &T_El_DecayPt);
        tree_.SetBranchAddress("T_El_DecayEta", &T_El_DecayEta);
        tree_.SetBranchAddress("T_El_ParentPt", &T_El_ParentPt);
        tree_.SetBranchAddress("T_El_ParentEta", &T_El_ParentEta);
#endif
    }

}
