from os.path import join, basename
from glob import glob
import sys

VERSION='0'
APPNAME='ZtoWll'

srcdir = '.'

program_file = 'main.cpp'

sources = [basename(i) for i in glob(join(srcdir, '*.cpp'))]
sources.remove(program_file)

blddir = 'build'

import Utils


def set_options(opt):
    opt.tool_options('compiler_cxx')

def configure(conf):
    conf.check_tool('compiler_cxx')
    # Check for ROOT

    rc = conf.find_program('root-config')
    conf.env['LIBPATH_ROOT'] = Utils.cmd_output("%s --libdir" % rc).strip()
    conf.env['CPPPATH_ROOT'] = Utils.cmd_output("%s --incdir" % rc).strip()
    conf.check_cxx(lib='Core', uselib_store='ROOT')
    print conf.env

def build(bld):
    task = bld.new_task_gen()
    task.features = 'cxx cprogram'
    task.source = sources + [program_file]
    task.target = APPNAME
    task.uselib = "ROOT"

